name: magma build

on:
#   schedule:
#   - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [orc8r, nms, feg, cwf, operator, agw, dp]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - run: ./build.sh ${{ matrix.build }}
